Train_config:
  train_name: 'diffusion unconditional'
  batch_size: 4 
  epochs : 500 
  lr : 0.0003
  device : cuda
  shaffle : True 
  intrable : 1
  num_sample : 3 # number of samples to generate mainly represented as n 
  model_ckpt  : /home/amzad/Desktop/diffusion/artifacts/model_ckpt/
  logs : /home/amzad/Desktop/diffusion/logs/
  figs : /home/amzad/Desktop/diffusion/fig/
  dataset : /home/amzad/Desktop/diffusion/dataset/images/
  ema_enable : True 
  ema : 0.999

Noise_schedule: 
  start : 0.0001
  end : 0.02
  steps : 1000
  device : cuda

Dir : 
  artifact_dir : /home/amzad/Desktop/diffusion/artifacts


Transform_config : 
  image_size : 64 
  resize : 80 
  crop : 64 
 
  mean : 
    - 0.5
    - 0.5
    - 0.5
  std :
    - 0.5
    - 0.5
    - 0.5
  to_tensor : True  



model_config: 
  cha_in: 3
  cha_out: 3 
  time_dim : 256 
  device: cuda 
  selfattn: 
    n_head: 4 
    batch_first: True

  dobule_conv:  
    kernel_size: 3 
    stride: 1 
    padding: 1 
    bias: True
  down: 
    kernel_size: 4 
    stride: 2 
    padding: 1 
    bias: False


    